### ISSUE TITLE
get_individual_data

### ISSUE THREAD

**Issue by bobd12** [EnergieID/energyid-py#1]
when using the API to get_individual_data(), I get following error: 
`requests.exceptions.HTTPError: 500 Server Error: Internal Server Error for url ...`.

the code I use and that previously worked is:
`'energyUse': group.get_individual_data('energyUse', start=start)`

**Comment by JrtPec** [comment]
The API was updated, the `end` parameter is now mandatory. It should work if you include it.

I've updated the code so `end` can no longer be `null` in this call.
